import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import Footer from "../components/footer/footer.component";
import Hero from "../components/hero/hero.component";
import Navbar from "../components/navbar/navbar.component";
import Testimonial from "../components/testimonial/testimonial.component";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Testimonial />
      <Footer />
    </>
  );
};

export default Home;
